baseURL: https://archer-n.github.io
languageCode: zh-cn
title: WangFan
theme: cactus # https://themes.gohugo.io/themes/hugo-theme-cactus/

# Default content language, support en (English) / zh (Chinese) / nl (Dutch), default 'en'
defaultContentLanguage: zh

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

# googleAnalytics: your-google-analytics-id
# disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2


menu:
  main:
    - name: Home
      url: /
      weight: 1

    - name: Writtings
      url: /posts
      weight: 2

    - name: Categories
      url: /categories
      weight: 3

    - name: Tags
      url: /tags
      weight: 4

    - name: About
      url: /about
      weight: 5

# Site parameters
params:
  colortheme: white # dark, light, white, or classic

  rss: true # generate rss feed. default value is false

  googleAnalyticsAsync: true # use asynchronous tracking. Synchronous tracking by default

  showAllPostsArchive: true # default

  # Home page settings
  description: "博学而笃志，切问而近思"

  mainSection: posts # your main section

  showAllPostsOnHomePage: false # default
  postsOnHomePage: 5 # this option will be ignored if showAllPostsOnHomePage is set to true

  tagsOverview: false # show tags overview by default.

  showProjectsList: true # show projects list by default (if projects data file exists).
  projectsUrl: https://github.com/archer-n # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat: "2006-01-02" # default

  # Post page settings
  show_updated: true # default
  showReadTime: true # default

  # Social links in footer, support github,twitter,stackoverflow,facebook
  social:
    # e.g.
    - name: github
      link: https://github.com/archer-n


staticDir:
  - assets/
